// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignedMessageSignature {
    /// R + S values concatenated
    #[serde(rename = "fullSig", skip_serializing_if = "Option::is_none")]
    pub full_sig: Option<String>,
    #[serde(rename = "r", skip_serializing_if = "Option::is_none")]
    pub r: Option<String>,
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<String>,
    #[serde(rename = "v", skip_serializing_if = "Option::is_none")]
    pub v: Option<V>,
}

impl SignedMessageSignature {
    pub fn new() -> SignedMessageSignature {
        SignedMessageSignature {
            full_sig: None,
            r: None,
            s: None,
            v: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize)]
pub enum V {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
}

/// Fireblocks serializes the recovery id as a JSON number in RAW signing
/// responses while other surfaces use the string form; accept both, and
/// accept the pre-EIP-155 legacy encoding (27/28) normalized to its parity.
impl<'de> serde::Deserialize<'de> for V {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = serde_json::Value::deserialize(deserializer)?;
        let numeric = match &value {
            serde_json::Value::String(text) => text.parse::<u64>().ok(),
            serde_json::Value::Number(number) => number.as_u64(),
            _ => None,
        };
        match numeric {
            Some(0) | Some(27) => Ok(Self::Variant0),
            Some(1) | Some(28) => Ok(Self::Variant1),
            _ => Err(serde::de::Error::custom(format!(
                "invalid signature v value: {value}"
            ))),
        }
    }
}

impl Default for V {
    fn default() -> V {
        Self::Variant0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deserializes_v_from_number() {
        let signature: SignedMessageSignature =
            serde_json::from_str(r#"{"r":"aa","s":"bb","v":1}"#).unwrap();
        assert_eq!(signature.v, Some(V::Variant1));
    }

    #[test]
    fn deserializes_v_from_string() {
        let signature: SignedMessageSignature =
            serde_json::from_str(r#"{"r":"aa","s":"bb","v":"0"}"#).unwrap();
        assert_eq!(signature.v, Some(V::Variant0));
    }

    #[test]
    fn deserializes_legacy_v_to_parity() {
        let signature: SignedMessageSignature =
            serde_json::from_str(r#"{"r":"aa","s":"bb","v":27}"#).unwrap();
        assert_eq!(signature.v, Some(V::Variant0));

        let signature: SignedMessageSignature =
            serde_json::from_str(r#"{"r":"aa","s":"bb","v":28}"#).unwrap();
        assert_eq!(signature.v, Some(V::Variant1));
    }

    #[test]
    fn rejects_out_of_range_v() {
        let result = serde_json::from_str::<SignedMessageSignature>(
            r#"{"r":"aa","s":"bb","v":29}"#,
        );
        assert!(
            matches!(result, Err(_)),
            "v=29 must be rejected, got {result:?}"
        );
    }
}
